export const creatorProjectsData = [
  {
    id: 'proj-1',
    title: 'E-Commerce Website',
    tags: ['React', 'Node', 'MongoDB'],
    category: 'Full-stack Dev',
    iconType: 'shopping-cart',
    iconBg: 'bg-orange-500/10 text-orange-400 border border-orange-500/20',
    status: 'In Progress',
    statusColor: 'bg-amber-500/10 text-amber-400 border border-amber-500/20',
    assignedEditor: {
      name: 'Rahul Verma',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    },
    progress: 68,
    deadline: '2026-09-18',
    budget: '₹45,000',
  },
  {
    id: 'proj-2',
    title: 'Social Media App',
    tags: ['Flutter', 'Firebase'],
    category: 'Mobile Dev',
    iconType: 'smartphone',
    iconBg: 'bg-pink-500/10 text-pink-400 border border-pink-500/20',
    status: 'Open',
    statusColor: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20',
    assignedEditor: null,
    progress: 20,
    deadline: '2026-09-28',
    budget: '₹35,000',
  },
  {
    id: 'proj-3',
    title: 'Portfolio Website',
    tags: ['React', 'Tailwind'],
    category: 'Frontend Dev',
    iconType: 'layout',
    iconBg: 'bg-blue-500/10 text-blue-400 border border-blue-500/20',
    status: 'Completed',
    statusColor: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20',
    assignedEditor: {
      name: 'Priya Mehta',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    },
    progress: 100,
    deadline: '2026-08-30',
    budget: '₹20,000',
  },
  {
    id: 'proj-4',
    title: 'YouTube 4K Documentary Cut',
    tags: ['Premiere Pro', 'Sound Design'],
    category: 'Video Editing',
    iconType: 'film',
    iconBg: 'bg-purple-500/10 text-purple-400 border border-purple-500/20',
    status: 'In Progress',
    statusColor: 'bg-amber-500/10 text-amber-400 border border-amber-500/20',
    assignedEditor: {
      name: 'Aditya Joshi',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    },
    progress: 45,
    deadline: '2026-09-12',
    budget: '₹28,000',
  }
];

export const editorRecommendedProjectsData = [
  {
    id: 'rec-1',
    title: 'Cinematic YouTube Travel Vlog (4K 60fps)',
    creator: 'Mark Goldbridge',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    budget: '₹24,000',
    deadline: '4 Days',
    tags: ['Premiere Pro', 'Color Grading', 'Sound Design'],
    proposalsCount: 6,
    difficulty: 'Intermediate',
    verified: true,
  },
  {
    id: 'rec-2',
    title: 'High-Retention TikTok / Instagram Reels Batch (10 Videos)',
    creator: 'Sarah Jenkins',
    creatorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    budget: '₹32,000',
    deadline: '3 Days',
    tags: ['After Effects', 'Alex Hormozi Style', 'Dynamic Captions'],
    proposalsCount: 14,
    difficulty: 'Expert',
    verified: true,
  },
  {
    id: 'rec-3',
    title: 'Tech Gadget Review & Unboxing Montage',
    creator: 'Dave Lee Studio',
    creatorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
    budget: '₹18,500',
    deadline: '5 Days',
    tags: ['DaVinci Resolve', 'Motion Graphics', 'B-Roll Sync'],
    proposalsCount: 9,
    difficulty: 'Intermediate',
    verified: true,
  }
];

export const editorActiveProjectsData = [
  {
    id: 'ed-act-1',
    title: 'Deep Dive: AI Revolution 2026',
    client: 'Nexus Media Corp',
    clientAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    progress: 75,
    dueDate: 'Sep 05, 2026',
    hoursRemaining: 34,
    status: 'Rough Cut Ready',
    budget: '₹22,000',
    deliverableType: '18 min MP4 4K',
  },
  {
    id: 'ed-act-2',
    title: 'Viral Reel Pack (Weekly Drop)',
    client: 'Chloe Adams',
    clientAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    progress: 40,
    dueDate: 'Sep 07, 2026',
    hoursRemaining: 78,
    status: 'B-Roll Insertion',
    budget: '₹15,000',
    deliverableType: '5x 9:16 Shorts',
  },
  {
    id: 'ed-act-3',
    title: 'SaaS Product Walkthrough Demo',
    client: 'CloudFlow Labs',
    clientAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    progress: 90,
    dueDate: 'Sep 04, 2026',
    hoursRemaining: 18,
    status: 'Final Audio Polish',
    budget: '₹28,000',
    deliverableType: '3 min Web Explainer',
  }
];

export const projectService = {
  getCreatorProjects: () => Promise.resolve(creatorProjectsData),
  getEditorRecommended: () => Promise.resolve(editorRecommendedProjectsData),
  getEditorActive: () => Promise.resolve(editorActiveProjectsData),
};
